# Data Standardisation
expected_orders_cols: # Renamed from mapping_orders_expected_cols
  Transaction ID: ["Transaction ID", "transaction_id"]
  Order ID: ["order_item_id", "Order ID", "order_id"]
  Product ID: ["Product ID", "product_id", "SKU", "Item Code", "product_id"]
  Quantity: ["Quantity", "Qty", "order_quantity", "quantity"]
  Total Amount: ["Total Amount", "total_amount", "amount"]
  Unit Price: ["unit_price", "price"]
  Order Date: ["Order Date", "order_date", "Order_date"]
  Discount Code Used: ["Discount Code Used", "discount_code_used", "promo_code"]
  Discount Value: ["Discount Value", "discount_value", "discount_amount"]
  Shipping Cost: ["Shipping Cost", "shipping_cost", "freight"]
  Total Payable: ["Total Payable", "total_payable", "amount_payable"]
  Return Status: ["Return Status", "return_stat", "is_returned"]
  Return Date: ["Return Date", "return_date"]

expected_transaction_cols: # Renamed from mapping_transactions_expected_cols
  Transaction ID: ["Transaction ID", "transaction_id"]
  Visit ID: ["Visit ID", "visit_id"]
  Order ID: ["Order ID", "order_id"]
  User ID: ["customer_id", "User ID", "user_id", "Customer ID"]
  Purchase Date: ["purchase_timestamp", "Purchase Date", "purchase_date", "Transaction Date"]
  Payment Method: ["Payment Method", "payment_method", "Mode of Payment"]
  Total Amount: ["total_payable","Total Payable", "total_payable", "Total_amount", "amount_payable", "Total_amount_per_transaction", "total_amount"]

orders_df_name: "Orders" # Renamed from df_name_orders
transactions_df_name: "Transactions" # Renamed from df_name_transactions

# Operations Parameters
at_risk_threshold_days: 70 # Customers with recency > this are considered at risk

# Churn Model Parameters
churn_inactive_days_threshold: 30
churn_model_n_estimators: 100
churn_model_random_state: 42
predicted_churn_probability_threshold: 0.5 

# Cox Model Parameters
cox_model_churn_threshold: 30 
cox_feature_cols:
  - aov
  - recency  
  - monetary
  - avg_days_between_orders
  - frequency


user_threshold_value: 0.5
threshold_metric: ['rfm_score']
selected_threshold_dict:
  recency: 30
  frequency: 5
  monetary: 100
  rfm_score: 50
inactive_days_threshold: 27

customer_col: User ID
date_col: Purchase Date
order_col: Transaction ID
amount_col: Total Amount